/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsPriceListsRouteImport } from './routes/_authenticated/settings/price-lists'
import { Route as AuthenticatedSettingsPosTerminalsRouteImport } from './routes/_authenticated/settings/pos-terminals'
import { Route as AuthenticatedSettingsPaymentMethodsRouteImport } from './routes/_authenticated/settings/payment-methods'
import { Route as AuthenticatedSettingsCurrenciesRouteImport } from './routes/_authenticated/settings/currencies'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings/company'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPriceListsRoute =
  AuthenticatedSettingsPriceListsRouteImport.update({
    id: '/settings/price-lists',
    path: '/settings/price-lists',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPosTerminalsRoute =
  AuthenticatedSettingsPosTerminalsRouteImport.update({
    id: '/settings/pos-terminals',
    path: '/settings/pos-terminals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPaymentMethodsRoute =
  AuthenticatedSettingsPaymentMethodsRouteImport.update({
    id: '/settings/payment-methods',
    path: '/settings/payment-methods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCurrenciesRoute =
  AuthenticatedSettingsCurrenciesRouteImport.update({
    id: '/settings/currencies',
    path: '/settings/currencies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/payment-methods': typeof AuthenticatedSettingsPaymentMethodsRoute
  '/settings/pos-terminals': typeof AuthenticatedSettingsPosTerminalsRoute
  '/settings/price-lists': typeof AuthenticatedSettingsPriceListsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/payment-methods': typeof AuthenticatedSettingsPaymentMethodsRoute
  '/settings/pos-terminals': typeof AuthenticatedSettingsPosTerminalsRoute
  '/settings/price-lists': typeof AuthenticatedSettingsPriceListsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/_authenticated/settings/payment-methods': typeof AuthenticatedSettingsPaymentMethodsRoute
  '/_authenticated/settings/pos-terminals': typeof AuthenticatedSettingsPosTerminalsRoute
  '/_authenticated/settings/price-lists': typeof AuthenticatedSettingsPriceListsRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/channels'
    | '/contacts'
    | '/dashboard'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/production'
    | '/products'
    | '/stock'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/payment-methods'
    | '/settings/pos-terminals'
    | '/settings/price-lists'
    | '/settings/users'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/channels'
    | '/contacts'
    | '/dashboard'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/production'
    | '/products'
    | '/stock'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/payment-methods'
    | '/settings/pos-terminals'
    | '/settings/price-lists'
    | '/settings/users'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/categories'
    | '/_authenticated/channels'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/stock'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/currencies'
    | '/_authenticated/settings/payment-methods'
    | '/_authenticated/settings/pos-terminals'
    | '/_authenticated/settings/price-lists'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/price-lists': {
      id: '/_authenticated/settings/price-lists'
      path: '/settings/price-lists'
      fullPath: '/settings/price-lists'
      preLoaderRoute: typeof AuthenticatedSettingsPriceListsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/pos-terminals': {
      id: '/_authenticated/settings/pos-terminals'
      path: '/settings/pos-terminals'
      fullPath: '/settings/pos-terminals'
      preLoaderRoute: typeof AuthenticatedSettingsPosTerminalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/payment-methods': {
      id: '/_authenticated/settings/payment-methods'
      path: '/settings/payment-methods'
      fullPath: '/settings/payment-methods'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/currencies': {
      id: '/_authenticated/settings/currencies'
      path: '/settings/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof AuthenticatedSettingsCurrenciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsCurrenciesRoute: typeof AuthenticatedSettingsCurrenciesRoute
  AuthenticatedSettingsPaymentMethodsRoute: typeof AuthenticatedSettingsPaymentMethodsRoute
  AuthenticatedSettingsPosTerminalsRoute: typeof AuthenticatedSettingsPosTerminalsRoute
  AuthenticatedSettingsPriceListsRoute: typeof AuthenticatedSettingsPriceListsRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsCurrenciesRoute: AuthenticatedSettingsCurrenciesRoute,
  AuthenticatedSettingsPaymentMethodsRoute:
    AuthenticatedSettingsPaymentMethodsRoute,
  AuthenticatedSettingsPosTerminalsRoute:
    AuthenticatedSettingsPosTerminalsRoute,
  AuthenticatedSettingsPriceListsRoute: AuthenticatedSettingsPriceListsRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
