/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsStockRouteImport } from './routes/_authenticated/settings/stock'
import { Route as AuthenticatedSettingsScaleRouteImport } from './routes/_authenticated/settings/scale'
import { Route as AuthenticatedSettingsPriceListsRouteImport } from './routes/_authenticated/settings/price-lists'
import { Route as AuthenticatedSettingsPosTerminalsRouteImport } from './routes/_authenticated/settings/pos-terminals'
import { Route as AuthenticatedSettingsPaymentMethodsRouteImport } from './routes/_authenticated/settings/payment-methods'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsCurrenciesRouteImport } from './routes/_authenticated/settings/currencies'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings/company'
import { Route as AuthenticatedSettingsAuditRouteImport } from './routes/_authenticated/settings/audit'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedContactsContactIdRouteImport } from './routes/_authenticated/contacts.$contactId'
import { Route as AuthenticatedSettingsPriceListsListIdRouteImport } from './routes/_authenticated/settings/price-lists.$listId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsStockRoute =
  AuthenticatedSettingsStockRouteImport.update({
    id: '/settings/stock',
    path: '/settings/stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsScaleRoute =
  AuthenticatedSettingsScaleRouteImport.update({
    id: '/settings/scale',
    path: '/settings/scale',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPriceListsRoute =
  AuthenticatedSettingsPriceListsRouteImport.update({
    id: '/settings/price-lists',
    path: '/settings/price-lists',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPosTerminalsRoute =
  AuthenticatedSettingsPosTerminalsRouteImport.update({
    id: '/settings/pos-terminals',
    path: '/settings/pos-terminals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPaymentMethodsRoute =
  AuthenticatedSettingsPaymentMethodsRouteImport.update({
    id: '/settings/payment-methods',
    path: '/settings/payment-methods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCurrenciesRoute =
  AuthenticatedSettingsCurrenciesRouteImport.update({
    id: '/settings/currencies',
    path: '/settings/currencies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAuditRoute =
  AuthenticatedSettingsAuditRouteImport.update({
    id: '/settings/audit',
    path: '/settings/audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedContactsContactIdRoute =
  AuthenticatedContactsContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)
const AuthenticatedSettingsPriceListsListIdRoute =
  AuthenticatedSettingsPriceListsListIdRouteImport.update({
    id: '/$listId',
    path: '/$listId',
    getParentRoute: () => AuthenticatedSettingsPriceListsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/pos': typeof AuthenticatedPosRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/payment-methods': typeof AuthenticatedSettingsPaymentMethodsRoute
  '/settings/pos-terminals': typeof AuthenticatedSettingsPosTerminalsRoute
  '/settings/price-lists': typeof AuthenticatedSettingsPriceListsRouteWithChildren
  '/settings/scale': typeof AuthenticatedSettingsScaleRoute
  '/settings/stock': typeof AuthenticatedSettingsStockRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/price-lists/$listId': typeof AuthenticatedSettingsPriceListsListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/pos': typeof AuthenticatedPosRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/payment-methods': typeof AuthenticatedSettingsPaymentMethodsRoute
  '/settings/pos-terminals': typeof AuthenticatedSettingsPosTerminalsRoute
  '/settings/price-lists': typeof AuthenticatedSettingsPriceListsRouteWithChildren
  '/settings/scale': typeof AuthenticatedSettingsScaleRoute
  '/settings/stock': typeof AuthenticatedSettingsStockRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/price-lists/$listId': typeof AuthenticatedSettingsPriceListsListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/payment-methods': typeof AuthenticatedSettingsPaymentMethodsRoute
  '/_authenticated/settings/pos-terminals': typeof AuthenticatedSettingsPosTerminalsRoute
  '/_authenticated/settings/price-lists': typeof AuthenticatedSettingsPriceListsRouteWithChildren
  '/_authenticated/settings/scale': typeof AuthenticatedSettingsScaleRoute
  '/_authenticated/settings/stock': typeof AuthenticatedSettingsStockRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/price-lists/$listId': typeof AuthenticatedSettingsPriceListsListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/channels'
    | '/contacts'
    | '/dashboard'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/pos'
    | '/production'
    | '/products'
    | '/recipes'
    | '/reports'
    | '/shifts'
    | '/stock'
    | '/super-admin'
    | '/transactions'
    | '/contacts/$contactId'
    | '/orders/$orderId'
    | '/settings/audit'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/payment-methods'
    | '/settings/pos-terminals'
    | '/settings/price-lists'
    | '/settings/scale'
    | '/settings/stock'
    | '/settings/users'
    | '/settings/'
    | '/settings/price-lists/$listId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/channels'
    | '/contacts'
    | '/dashboard'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/pos'
    | '/production'
    | '/products'
    | '/recipes'
    | '/reports'
    | '/shifts'
    | '/stock'
    | '/super-admin'
    | '/transactions'
    | '/contacts/$contactId'
    | '/orders/$orderId'
    | '/settings/audit'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/payment-methods'
    | '/settings/pos-terminals'
    | '/settings/price-lists'
    | '/settings/scale'
    | '/settings/stock'
    | '/settings/users'
    | '/settings'
    | '/settings/price-lists/$listId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/categories'
    | '/_authenticated/channels'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/pos'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/recipes'
    | '/_authenticated/reports'
    | '/_authenticated/shifts'
    | '/_authenticated/stock'
    | '/_authenticated/super-admin'
    | '/_authenticated/transactions'
    | '/_authenticated/contacts/$contactId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/settings/audit'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/currencies'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/payment-methods'
    | '/_authenticated/settings/pos-terminals'
    | '/_authenticated/settings/price-lists'
    | '/_authenticated/settings/scale'
    | '/_authenticated/settings/stock'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/price-lists/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/stock': {
      id: '/_authenticated/settings/stock'
      path: '/settings/stock'
      fullPath: '/settings/stock'
      preLoaderRoute: typeof AuthenticatedSettingsStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/scale': {
      id: '/_authenticated/settings/scale'
      path: '/settings/scale'
      fullPath: '/settings/scale'
      preLoaderRoute: typeof AuthenticatedSettingsScaleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/price-lists': {
      id: '/_authenticated/settings/price-lists'
      path: '/settings/price-lists'
      fullPath: '/settings/price-lists'
      preLoaderRoute: typeof AuthenticatedSettingsPriceListsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/pos-terminals': {
      id: '/_authenticated/settings/pos-terminals'
      path: '/settings/pos-terminals'
      fullPath: '/settings/pos-terminals'
      preLoaderRoute: typeof AuthenticatedSettingsPosTerminalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/payment-methods': {
      id: '/_authenticated/settings/payment-methods'
      path: '/settings/payment-methods'
      fullPath: '/settings/payment-methods'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/currencies': {
      id: '/_authenticated/settings/currencies'
      path: '/settings/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof AuthenticatedSettingsCurrenciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/audit': {
      id: '/_authenticated/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AuthenticatedSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/contacts/$contactId': {
      id: '/_authenticated/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthenticatedContactsContactIdRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/_authenticated/settings/price-lists/$listId': {
      id: '/_authenticated/settings/price-lists/$listId'
      path: '/$listId'
      fullPath: '/settings/price-lists/$listId'
      preLoaderRoute: typeof AuthenticatedSettingsPriceListsListIdRouteImport
      parentRoute: typeof AuthenticatedSettingsPriceListsRoute
    }
  }
}

interface AuthenticatedContactsRouteChildren {
  AuthenticatedContactsContactIdRoute: typeof AuthenticatedContactsContactIdRoute
}

const AuthenticatedContactsRouteChildren: AuthenticatedContactsRouteChildren = {
  AuthenticatedContactsContactIdRoute: AuthenticatedContactsContactIdRoute,
}

const AuthenticatedContactsRouteWithChildren =
  AuthenticatedContactsRoute._addFileChildren(
    AuthenticatedContactsRouteChildren,
  )

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedSettingsPriceListsRouteChildren {
  AuthenticatedSettingsPriceListsListIdRoute: typeof AuthenticatedSettingsPriceListsListIdRoute
}

const AuthenticatedSettingsPriceListsRouteChildren: AuthenticatedSettingsPriceListsRouteChildren =
  {
    AuthenticatedSettingsPriceListsListIdRoute:
      AuthenticatedSettingsPriceListsListIdRoute,
  }

const AuthenticatedSettingsPriceListsRouteWithChildren =
  AuthenticatedSettingsPriceListsRoute._addFileChildren(
    AuthenticatedSettingsPriceListsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedSettingsAuditRoute: typeof AuthenticatedSettingsAuditRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsCurrenciesRoute: typeof AuthenticatedSettingsCurrenciesRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPaymentMethodsRoute: typeof AuthenticatedSettingsPaymentMethodsRoute
  AuthenticatedSettingsPosTerminalsRoute: typeof AuthenticatedSettingsPosTerminalsRoute
  AuthenticatedSettingsPriceListsRoute: typeof AuthenticatedSettingsPriceListsRouteWithChildren
  AuthenticatedSettingsScaleRoute: typeof AuthenticatedSettingsScaleRoute
  AuthenticatedSettingsStockRoute: typeof AuthenticatedSettingsStockRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedSettingsAuditRoute: AuthenticatedSettingsAuditRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsCurrenciesRoute: AuthenticatedSettingsCurrenciesRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsPaymentMethodsRoute:
    AuthenticatedSettingsPaymentMethodsRoute,
  AuthenticatedSettingsPosTerminalsRoute:
    AuthenticatedSettingsPosTerminalsRoute,
  AuthenticatedSettingsPriceListsRoute:
    AuthenticatedSettingsPriceListsRouteWithChildren,
  AuthenticatedSettingsScaleRoute: AuthenticatedSettingsScaleRoute,
  AuthenticatedSettingsStockRoute: AuthenticatedSettingsStockRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
